### ISSUE TITLE
Data Explorer Task Tracker

### ISSUE THREAD

**Issue by brutusyhy** [brutusyhy/polars-explorer#12]
Data Explorer Panel is the main area where the user engages with the data, and thus providing convenience of use and functionality is crucial.

A. Data Table
- [ ] 1. Resizable Columns
- [ ] 2. Highlight Column On Hovering Cell
- [ ] 3. Clickable Column sort
- [ ] 4. Column context menu for common types of queries

B. Data Visualization
This is still an early conception: I'm not sure whether it's better to display visualization in the app's panel, or create pop-up window for graphs. It is also not an immediate concern 

C. Better Pagination/Navigation
- [ ] 1. Change Page Size
- [ ] 2. Go to specific row

D. Search Tool
To create a good search tool under my strategy requires some clever planning, so it will be postponed for the time.
